db:
  image: carloscastillo/rgt-oracle-xe-11g:latest
  ports:
    - "15080:8080"
    - "1521:1521"
  environment:
    - processes=200
    - SCHEMAS=sample
    - BATCH_PARAMS=World
  volumes:
    - .oracle_data:/u01/app/oracle
